services:
  api:
    image: viet-tts:latest
    build: .
    restart: always
    container_name: viet-tts-service
    ports:
      - 8298:8298
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - TTS_NUM_WORKERS=1
    volumes:
      - ./pretrained-models:/app/pretrained-models
      - ./samples:/app/samples
      - ./src:/app/src
      - ./web:/app/web
    command: gunicorn src.server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8298 --workers 1 --max-requests 1000 --max-requests-jitter 50 --timeout 300 --keep-alive 75 --graceful-timeout 60

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    container_name: viet-tts-tunnel
    depends_on:
      - api
    command: tunnel --no-autoupdate --url http://api:8298